name: hr_app_redo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  freezed_annotation: ^2.4.2
  go_router: ^14.2.0
  json_annotation: ^4.9.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  font_awesome_flutter: ^10.7.0
  url_launcher: ^6.1.6
  google_sign_in: ^6.2.1
  flutter_localization: ^0.2.0
  flutter_native_splash: ^2.1.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.8.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/a.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/a.png
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
