// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYNOPiGpZ1zF83aFRBkx4uVx7WeaSMIi0',
    appId: '1:521621509248:web:6bb0ed9dbd459608428265',
    messagingSenderId: '521621509248',
    projectId: 'hrmanagement-bc458',
    authDomain: 'hrmanagement-bc458.firebaseapp.com',
    storageBucket: 'hrmanagement-bc458.appspot.com',
    measurementId: 'G-7BK9ESJ9TP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA7gSUg8bzBACTMb3eIzkeYNxExjUfUOU',
    appId: '1:521621509248:android:958c11e4264c9f3d428265',
    messagingSenderId: '521621509248',
    projectId: 'hrmanagement-bc458',
    storageBucket: 'hrmanagement-bc458.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVUKmj_HygxVpkP753qFjQvqiqo_QJbN4',
    appId: '1:521621509248:ios:55163ee8726a14c1428265',
    messagingSenderId: '521621509248',
    projectId: 'hrmanagement-bc458',
    storageBucket: 'hrmanagement-bc458.appspot.com',
    androidClientId: '521621509248-knsjgnp10e9mhsasg2micv0b9b5s5g26.apps.googleusercontent.com',
    iosClientId: '521621509248-aujja0925t3k8hqqlcakdb64vjvrfj2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrAppRedo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVUKmj_HygxVpkP753qFjQvqiqo_QJbN4',
    appId: '1:521621509248:ios:55163ee8726a14c1428265',
    messagingSenderId: '521621509248',
    projectId: 'hrmanagement-bc458',
    storageBucket: 'hrmanagement-bc458.appspot.com',
    androidClientId: '521621509248-knsjgnp10e9mhsasg2micv0b9b5s5g26.apps.googleusercontent.com',
    iosClientId: '521621509248-aujja0925t3k8hqqlcakdb64vjvrfj2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.hrAppRedo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYNOPiGpZ1zF83aFRBkx4uVx7WeaSMIi0',
    appId: '1:521621509248:web:acb692733f8a347c428265',
    messagingSenderId: '521621509248',
    projectId: 'hrmanagement-bc458',
    authDomain: 'hrmanagement-bc458.firebaseapp.com',
    storageBucket: 'hrmanagement-bc458.appspot.com',
    measurementId: 'G-RSQNPMR40B',
  );

}